### PR TITLE
Mangle base64 test assets with spaces and new-lines like production ones

### PR DESCRIPTION
**Pull request by Slamdunk**
Real values have white spaces within base64 values, so test assets should reflect this.

Note that this build will fail because the issue must be addressed on `xml-common` (which I will within minutes) but it is also safe to have a real test assets here.

### CODE REVIEW

**Comment by tvdijen** [comment]
I'm kinda surprised this fails.. I was under the impression that I had fixed it by storing the raw base64-value
Real test assets are very much welcome though, so thanks!!

**Comment by tvdijen** [comment]
I think the whole fix is to have the XMLBase64ElementTrait in `xml-common` use getRawContent() in the toXML()-method instead of the sanitized getContent()

**Comment by Slamdunk** [comment]
The opposite: the issue is that it calls `\SimpleSAML\XML\XMLStringElementTrait::setContent` which checks the unsanitized content.

I'm on my way for a test suite for it.

**Comment by Slamdunk** [comment]
Blocked by https://github.com/simplesamlphp/xml-common/pull/7

**Comment by tvdijen** [comment]
Unfortunately the tests still don't pass

**Comment by Slamdunk** [comment]
Of course: https://github.com/simplesamlphp/xml-common/pull/7 only allowed base64 to have whitespaces, but now here I need to fix tests assertions to have them too.

It is unfortunate that a re-run on Github Actions deletes the previous run, otherwise you would have seen that this error is no more present:

```
1) SimpleSAML\XMLSecurity\Test\XML\ds\DigestValueTest::testUnmarshalling
SimpleSAML\Assert\AssertionFailedException: '
/CTj03d1DB5e2t7CTo9BEzCf5S9NRzwnBgZRlm32REI=
' is not a valid Base64 encoded string

/vendor/simplesamlphp/assert/src/Assert.php:46
/vendor/simplesamlphp/xml-common/src/XMLBase64ElementTrait.php:80
/vendor/simplesamlphp/xml-common/src/XMLStringElementTrait.php:39
/vendor/simplesamlphp/xml-common/src/XMLBase64ElementTrait.php:31
/vendor/simplesamlphp/xml-common/src/XMLStringElementTrait.php:85
/tests/XML/ds/DigestValueTest.php:65
```

**Comment by Slamdunk** [comment]
Here the full diff of PHPUnit runs before and after `xml-common:v0.5.5`:

```diff
--- /tmp/tmp.A3mCtXje9m/1       2021-04-30 15:58:51.174329904 +0200
+++ /tmp/tmp.A3mCtXje9m/2       2021-04-30 15:59:30.110472119 +0200
@@ -2,142 +2,10 @@
 PHPUnit 9.5.4 by Sebastian Bergmann and contributors.

 ...............................................................  63 / 164 ( 38%)
-...............F.EE...............F.EE..........F.EE...FEE..... 126 / 164 ( 76%)
+...............F..................F.............F......F....... 126 / 164 ( 76%)
 ......................................                          164 / 164 (100%)

-Time: 00:03.986, Memory: 34.00 MB
-
-There were 8 errors:
-
-1) SimpleSAML\XMLSecurity\Test\XML\ds\DigestValueTest::testUnmarshalling
-SimpleSAML\Assert\AssertionFailedException: '
-/CTj03d1DB5e2t7CTo9BEzCf5S9NRzwnBgZRlm32REI=
-' is not a valid Base64 encoded string
-
-/vendor/simplesamlphp/assert/src/Assert.php:46
-/vendor/simplesamlphp/xml-common/src/XMLBase64ElementTrait.php:80
-/vendor/simplesamlphp/xml-common/src/XMLStringElementTrait.php:39
-/vendor/simplesamlphp/xml-common/src/XMLBase64ElementTrait.php:31
-/vendor/simplesamlphp/xml-common/src/XMLStringElementTrait.php:85
-/tests/XML/ds/DigestValueTest.php:65
-
-2) SimpleSAML\XMLSecurity\Test\XML\ds\DigestValueTest::testSerialization
-SimpleSAML\Assert\AssertionFailedException: '
-/CTj03d1DB5e2t7CTo9BEzCf5S9NRzwnBgZRlm32REI=
-' is not a valid Base64 encoded string
-
-/vendor/simplesamlphp/assert/src/Assert.php:46
-/vendor/simplesamlphp/xml-common/src/XMLBase64ElementTrait.php:80
-/vendor/simplesamlphp/xml-common/src/XMLStringElementTrait.php:39
-/vendor/simplesamlphp/xml-common/src/XMLBase64ElementTrait.php:31
-/vendor/simplesamlphp/xml-common/src/XMLStringElementTrait.php:85
-/vendor/simplesamlphp/xml-common/tests/PHPUnit/SerializableXMLTestTrait.php:46
-
-3) SimpleSAML\XMLSecurity\Test\XML\ds\SignatureValueTest::testUnmarshalling
-SimpleSAML\Assert\AssertionFailedException: '
-j14G9v6AnsOiEJYgkTg864DG3e/KLqoGpuybPGSGblVTn7ST6M/BsvP7YiVZjLqJEuEvWmf2mW4D
-Pb+pbArzzDcsLWEtNveMrw+FkWehDUQV9oe20iepo+W46wmj7zB/eWL+Z8MrGvlycoTndJU6CVwH
-TLsB+dq2FDa7JV4pAPjMY32JZTbiwKhzqw3nEi/eVrujJE4YRrlW28D+rXhITfoUAGGvsqPzcwGz
-p02lnMe2SmXADY1u9lbVjOhUrJpgvWfn9YuiCR+wjvaGMwIwzfJxChLJZOBV+1ad1CyNTiu6qAbl
-xZ4F8cWlMWJ7f0KkWvtw66HOf2VNR6Qan2Ra7Q==
-' is not a valid Base64 encoded string
-
-/vendor/simplesamlphp/assert/src/Assert.php:46
-/vendor/simplesamlphp/xml-common/src/XMLBase64ElementTrait.php:80
-/vendor/simplesamlphp/xml-common/src/XMLStringElementTrait.php:39
-/vendor/simplesamlphp/xml-common/src/XMLBase64ElementTrait.php:31
-/vendor/simplesamlphp/xml-common/src/XMLStringElementTrait.php:85
-/tests/XML/ds/SignatureValueTest.php:74
-
-4) SimpleSAML\XMLSecurity\Test\XML\ds\SignatureValueTest::testSerialization
-SimpleSAML\Assert\AssertionFailedException: '
-j14G9v6AnsOiEJYgkTg864DG3e/KLqoGpuybPGSGblVTn7ST6M/BsvP7YiVZjLqJEuEvWmf2mW4D
-Pb+pbArzzDcsLWEtNveMrw+FkWehDUQV9oe20iepo+W46wmj7zB/eWL+Z8MrGvlycoTndJU6CVwH
-TLsB+dq2FDa7JV4pAPjMY32JZTbiwKhzqw3nEi/eVrujJE4YRrlW28D+rXhITfoUAGGvsqPzcwGz
-p02lnMe2SmXADY1u9lbVjOhUrJpgvWfn9YuiCR+wjvaGMwIwzfJxChLJZOBV+1ad1CyNTiu6qAbl
-xZ4F8cWlMWJ7f0KkWvtw66HOf2VNR6Qan2Ra7Q==
-' is not a valid Base64 encoded string
-
-/vendor/simplesamlphp/assert/src/Assert.php:46
-/vendor/simplesamlphp/xml-common/src/XMLBase64ElementTrait.php:80
-/vendor/simplesamlphp/xml-common/src/XMLStringElementTrait.php:39
-/vendor/simplesamlphp/xml-common/src/XMLBase64ElementTrait.php:31
-/vendor/simplesamlphp/xml-common/src/XMLStringElementTrait.php:85
-/vendor/simplesamlphp/xml-common/tests/PHPUnit/SerializableXMLTestTrait.php:46
-
-5) SimpleSAML\XMLSecurity\Test\XML\ds\X509CertificateTest::testUnmarshalling
-SimpleSAML\Assert\AssertionFailedException: '
-MIICxDCCAi2gAwIBAgIUCJ8EYI/BrvQnHt9QFGfdqgaxDmowDQYJKoZIhvcNAQELBQAwczElMCMG
-A1UEAwwcc2VsZnNpZ25lZC5zaW1wbGVzYW1scGhwLm9yZzEZMBcGA1UECgwQU2ltcGxlU0FNTHBo
-cCBIUTERMA8GA1UEBwwISG9ub2x1bHUxDzANBgNVBAgMBkhhd2FpaTELMAkGA1UEBhMCVVMwIBcN
-MjAwNjIzMjEwMTEyWhgPMjEyMDA1MzAyMTAxMTJaMHMxJTAjBgNVBAMMHHNlbGZzaWduZWQuc2lt
-cGxlc2FtbHBocC5vcmcxGTAXBgNVBAoMEFNpbXBsZVNBTUxwaHAgSFExETAPBgNVBAcMCEhvbm9s
-dWx1MQ8wDQYDVQQIDAZIYXdhaWkxCzAJBgNVBAYTAlVTMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCB
-iQKBgQDZ3ztmRqrJm6zSJ2jNUjbxdlX3WLadthHvDkdfQDWuFIUjMkCfO8+OWYdFP4cQWKBVnWyO
-+/LXFl9p9fwcSJmhmkgz5blUw0cjv8jccHw+yfVnGxGCK2Up/Si4HE/WStgjTKr3ivAqyc0Kc/97
-EoIXmb96SEEb4Lat9xt6mFSbWQIDAQABo1MwUTAdBgNVHQ4EFgQUHhB/tFwoDOT8V1nLi5XY4CJg
-TTQwHwYDVR0jBBgwFoAUHhB/tFwoDOT8V1nLi5XY4CJgTTQwDwYDVR0TAQH/BAUwAwEB/zANBgkq
-hkiG9w0BAQsFAAOBgQBVqkGuiwyYMx0FH3j/qirZ2nKrjUU+p0ganzEA7kVZ97RivW5SFLHkRjcf
-qDXVyqOzmr4iR8rfxI2rUjYQI1SsKacPhitiArMk2IQ+uvxZ5eNtU2yFzW4arQ+a2ttlZI/GF9nL
-vgUNFIUwaDc+PQD2rOk+ACklbAS3jkf+L3DpQg==
-' is not a valid Base64 encoded string
-
-/vendor/simplesamlphp/assert/src/Assert.php:46
-/vendor/simplesamlphp/xml-common/src/XMLBase64ElementTrait.php:80
-/vendor/simplesamlphp/xml-common/src/XMLStringElementTrait.php:39
-/vendor/simplesamlphp/xml-common/src/XMLBase64ElementTrait.php:31
-/vendor/simplesamlphp/xml-common/src/XMLStringElementTrait.php:85
-/tests/XML/ds/X509CertificateTest.php:90
-
-6) SimpleSAML\XMLSecurity\Test\XML\ds\X509CertificateTest::testSerialization
-SimpleSAML\Assert\AssertionFailedException: '
-MIICxDCCAi2gAwIBAgIUCJ8EYI/BrvQnHt9QFGfdqgaxDmowDQYJKoZIhvcNAQELBQAwczElMCMG
-A1UEAwwcc2VsZnNpZ25lZC5zaW1wbGVzYW1scGhwLm9yZzEZMBcGA1UECgwQU2ltcGxlU0FNTHBo
-cCBIUTERMA8GA1UEBwwISG9ub2x1bHUxDzANBgNVBAgMBkhhd2FpaTELMAkGA1UEBhMCVVMwIBcN
-MjAwNjIzMjEwMTEyWhgPMjEyMDA1MzAyMTAxMTJaMHMxJTAjBgNVBAMMHHNlbGZzaWduZWQuc2lt
-cGxlc2FtbHBocC5vcmcxGTAXBgNVBAoMEFNpbXBsZVNBTUxwaHAgSFExETAPBgNVBAcMCEhvbm9s
-dWx1MQ8wDQYDVQQIDAZIYXdhaWkxCzAJBgNVBAYTAlVTMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCB
-iQKBgQDZ3ztmRqrJm6zSJ2jNUjbxdlX3WLadthHvDkdfQDWuFIUjMkCfO8+OWYdFP4cQWKBVnWyO
-+/LXFl9p9fwcSJmhmkgz5blUw0cjv8jccHw+yfVnGxGCK2Up/Si4HE/WStgjTKr3ivAqyc0Kc/97
-EoIXmb96SEEb4Lat9xt6mFSbWQIDAQABo1MwUTAdBgNVHQ4EFgQUHhB/tFwoDOT8V1nLi5XY4CJg
-TTQwHwYDVR0jBBgwFoAUHhB/tFwoDOT8V1nLi5XY4CJgTTQwDwYDVR0TAQH/BAUwAwEB/zANBgkq
-hkiG9w0BAQsFAAOBgQBVqkGuiwyYMx0FH3j/qirZ2nKrjUU+p0ganzEA7kVZ97RivW5SFLHkRjcf
-qDXVyqOzmr4iR8rfxI2rUjYQI1SsKacPhitiArMk2IQ+uvxZ5eNtU2yFzW4arQ+a2ttlZI/GF9nL
-vgUNFIUwaDc+PQD2rOk+ACklbAS3jkf+L3DpQg==
-' is not a valid Base64 encoded string
-
-/vendor/simplesamlphp/assert/src/Assert.php:46
-/vendor/simplesamlphp/xml-common/src/XMLBase64ElementTrait.php:80
-/vendor/simplesamlphp/xml-common/src/XMLStringElementTrait.php:39
-/vendor/simplesamlphp/xml-common/src/XMLBase64ElementTrait.php:31
-/vendor/simplesamlphp/xml-common/src/XMLStringElementTrait.php:85
-/vendor/simplesamlphp/xml-common/tests/PHPUnit/SerializableXMLTestTrait.php:46
-
-7) SimpleSAML\XMLSecurity\Test\XML\ds\X509DigestTest::testUnmarshalling
-SimpleSAML\Assert\AssertionFailedException: '
-NllYUDA9XclmzMa84vOTdA3aunzwxBIqYjktnHBPcso=
-' is not a valid Base64 encoded string
-
-/vendor/simplesamlphp/assert/src/Assert.php:46
-/vendor/simplesamlphp/xml-common/src/XMLBase64ElementTrait.php:80
-/vendor/simplesamlphp/xml-common/src/XMLStringElementTrait.php:39
-/src/XML/ds/X509Digest.php:39
-/src/XML/ds/X509Digest.php:96
-/tests/XML/ds/X509DigestTest.php:69
-
-8) SimpleSAML\XMLSecurity\Test\XML\ds\X509DigestTest::testSerialization
-SimpleSAML\Assert\AssertionFailedException: '
-NllYUDA9XclmzMa84vOTdA3aunzwxBIqYjktnHBPcso=
-' is not a valid Base64 encoded string
-
-/vendor/simplesamlphp/assert/src/Assert.php:46
-/vendor/simplesamlphp/xml-common/src/XMLBase64ElementTrait.php:80
-/vendor/simplesamlphp/xml-common/src/XMLStringElementTrait.php:39
-/src/XML/ds/X509Digest.php:39
-/src/XML/ds/X509Digest.php:96
-/vendor/simplesamlphp/xml-common/tests/PHPUnit/SerializableXMLTestTrait.php:46
-
---
+Time: 00:00.618, Memory: 34.00 MB

 There were 4 failures:

@@ -205,5 +73,5 @@

 /tests/XML/ds/X509DigestTest.php:60

-ERRORS!
-Tests: 164, Assertions: 325, Errors: 8, Failures: 4.
+FAILURES!
+Tests: 164, Assertions: 334, Failures: 4.
```

**Comment by tvdijen** [comment]
Ah, I see!
Actually, since the trait is properly unit tested for both cases, I think this PR has become redundant

**Comment by Slamdunk** [comment]
>  Actually, since the trait is properly unit tested for both cases, I think this PR has become redundant

I think not!
This serves as an integration test. On `xml-common` I made datasets up, here instead they are kinda real.
Let me fix the assertions please and wait for the green build.

**Comment by Slamdunk** [comment]
Another run approval required :roll_eyes:

**Comment by tvdijen** [comment]
Thanks @Slamdunk ! Your contributions are much appreciated!

**Pull request merged**
